/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import form.FormClient;
import form.FormClientModifier;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login.Admin;
import login.Authentification;

/**
 *
 * @author RANDRIAMANANTSOA
 */
public class Client extends javax.swing.JFrame {

    Connecter con = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();

    public Client() {
        initComponents();
        model.addColumn("Id");
        model.addColumn("Nom Client");
        model.addColumn("Adresse");
        model.addColumn("Contact");

        try {
            stm = con.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("select * from client");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("idClient"), Rs.getString("nomClient"), Rs.getString("addresse"), Rs.getString("contact")});
            }

        } catch (SQLException e) {
            System.err.println(e);
        }

        tblClient.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuEtat = new javax.swing.JLabel();
        menuEntree = new javax.swing.JLabel();
        menuSortie = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        txt_rechercheClient = new javax.swing.JTextField();
        lbl_clientRecherche = new javax.swing.JLabel();
        btn_clientAjouter = new javax.swing.JButton();
        btn_clientModifier = new javax.swing.JButton();
        btn_clientSupprimer = new javax.swing.JButton();
        btn_clientActualiser = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        menuAdmin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuProduit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(121, 45, 49));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuEtat.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuEtat.setForeground(new java.awt.Color(255, 255, 255));
        menuEtat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sales Performance_50px.png"))); // NOI18N
        menuEtat.setText("ETAT");
        menuEtat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEtatMouseClicked(evt);
            }
        });
        jPanel1.add(menuEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, -1));

        menuEntree.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuEntree.setForeground(new java.awt.Color(255, 255, 255));
        menuEntree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jog Forward_48px.png"))); // NOI18N
        menuEntree.setText("ENTREE");
        menuEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEntreeMouseClicked(evt);
            }
        });
        jPanel1.add(menuEntree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, -1));

        menuSortie.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuSortie.setForeground(new java.awt.Color(255, 255, 255));
        menuSortie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jog Reverse_48px.png"))); // NOI18N
        menuSortie.setText("SORTIE");
        menuSortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSortieMouseClicked(evt);
            }
        });
        jPanel1.add(menuSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 140, 380));

        jPanel2.setBackground(new java.awt.Color(176, 143, 135));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_100px.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Male User_100px.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 100));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CLIENTS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 160, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 930, 100));

        jPanel3.setBackground(new java.awt.Color(246, 144, 42));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClient);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 640, 240));
        jPanel3.add(txt_rechercheClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 30));

        lbl_clientRecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search_35px.png"))); // NOI18N
        lbl_clientRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clientRechercheMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_clientRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        btn_clientAjouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clientAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Plus_35px.png"))); // NOI18N
        btn_clientAjouter.setText("NOUVEAU");
        btn_clientAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientAjouterActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clientAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 40));

        btn_clientModifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clientModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit_35px.png"))); // NOI18N
        btn_clientModifier.setText("MODIFIER");
        btn_clientModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientModifierActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clientModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 160, 40));

        btn_clientSupprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clientSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete_35px.png"))); // NOI18N
        btn_clientSupprimer.setText("SUPPRIMER");
        btn_clientSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientSupprimerActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clientSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 150, 40));

        btn_clientActualiser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clientActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Synchronize_48px.png"))); // NOI18N
        btn_clientActualiser.setText("ACTUALISER");
        btn_clientActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientActualiserActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clientActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 180, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 660, 380));

        jPanel4.setBackground(new java.awt.Color(176, 143, 135));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 479, 930, 100));

        jPanel5.setBackground(new java.awt.Color(121, 45, 49));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuAdmin.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuAdmin.setForeground(new java.awt.Color(255, 255, 255));
        menuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer_50px.png"))); // NOI18N
        menuAdmin.setText("COMPTE");
        menuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdminMouseClicked(evt);
            }
        });
        jPanel5.add(menuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hard Working_48px.png"))); // NOI18N
        jLabel6.setText("CLIENT");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, -1));

        menuProduit.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuProduit.setForeground(new java.awt.Color(255, 255, 255));
        menuProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Buying_48px.png"))); // NOI18N
        menuProduit.setText("PRODUIT");
        menuProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProduitMouseClicked(evt);
            }
        });
        jPanel5.add(menuProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 110, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void affiche() {
        try {
            model.setRowCount(0);
            stm = con.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("select * from client");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("idClient"), Rs.getString("nomClient"), Rs.getString("addresse"), Rs.getString("contact")});
            }
        } catch (SQLException e) {
            System.err.println(e);
        }

        tblClient.setModel(model);
    }
    private void menuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdminMouseClicked
        new Admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAdminMouseClicked

    private void menuProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProduitMouseClicked
        new Produit().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuProduitMouseClicked

    private void menuEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEntreeMouseClicked
        new Entree().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEntreeMouseClicked

    private void menuSortieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSortieMouseClicked
        new Sortie().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuSortieMouseClicked

    private void menuEtatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEtatMouseClicked
        new Etat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEtatMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Authentification().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void btn_clientAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientAjouterActionPerformed
        new FormClient().setVisible(true);
    }//GEN-LAST:event_btn_clientAjouterActionPerformed

    private void btn_clientModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientModifierActionPerformed
        TableModel model1 = tblClient.getModel();
        int indexs[] = tblClient.getSelectedRows();

        Object[] row = new Object[1];
        FormClientModifier frm2 = new FormClientModifier();
        for (int i = 0; i < indexs.length; i++) {
            FormClientModifier.txt_cliIdModifier.setText((String) model1.getValueAt(indexs[i], 0));
            FormClientModifier.txt_cliNomModifier.setText((String) model1.getValueAt(indexs[i], 1));
            FormClientModifier.txt_cliAdresseModifier.setText((String) model1.getValueAt(indexs[i], 2));
            FormClientModifier.txt_cliContactModifier.setText((String) model1.getValueAt(indexs[i], 3));
        }
        frm2.setVisible(true);
    }//GEN-LAST:event_btn_clientModifierActionPerformed

    private void btn_clientSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientSupprimerActionPerformed
        TableModel model1 = tblClient.getModel();
        int indexs[] = tblClient.getSelectedRows();
        String id, nom, adr, contact;
        Object[] row = new Object[1];

        for (int i = 0; i < indexs.length; i++) {
            id = (String) model1.getValueAt(indexs[i], 0);
            nom = (String) model1.getValueAt(indexs[i], 1);
            adr = (String) model1.getValueAt(indexs[i], 2);
            contact = (String) model1.getValueAt(indexs[i], 3);
            try {
                stm = con.obtenirConnexion().createStatement();
                if (JOptionPane.showConfirmDialog(null, "Vous voulez vraiment supprimer", "suppression",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    if (id.length() != 0) {
                        stm.executeUpdate("DELETE from client WHERE idClient=" + id);
                        affiche();
                    } else {
                        JOptionPane.showConfirmDialog(null, "Veuillez remplir le champ id");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erreur de suppression !" + e.getMessage());
                System.err.println(e);
            }
        }

    }//GEN-LAST:event_btn_clientSupprimerActionPerformed

    private void btn_clientActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientActualiserActionPerformed
        affiche();
    }//GEN-LAST:event_btn_clientActualiserActionPerformed

    private void lbl_clientRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clientRechercheMouseClicked
        try {
            model.setRowCount(0);
            {
                Rs = stm.executeQuery("SELECT * from client WHERE nomClient LIKE '%" + txt_rechercheClient.getText() + "%' OR addresse LIKE '%" + txt_rechercheClient.getText() + "%' ");
                txt_rechercheClient.setText("");
            }
            while (Rs.next()) {
                Object[] client = {Rs.getString("idClient"), Rs.getString("nomClient"), Rs.getString("addresse"), Rs.getString("contact")};
                model.addRow(client);
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Aucun client correspond!");
                }
            }
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_clientRechercheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clientActualiser;
    private javax.swing.JButton btn_clientAjouter;
    private javax.swing.JButton btn_clientModifier;
    private javax.swing.JButton btn_clientSupprimer;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_clientRecherche;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuAdmin;
    private javax.swing.JLabel menuEntree;
    private javax.swing.JLabel menuEtat;
    private javax.swing.JLabel menuProduit;
    private javax.swing.JLabel menuSortie;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextField txt_rechercheClient;
    // End of variables declaration//GEN-END:variables
}
