/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import login.Admin;
import login.Authentification;

/**
 *
 * @author RANDRIAMANANTSOA
 */
public class Etat extends javax.swing.JFrame {

    Connecter con = new Connecter();
    Statement stm, stm1, stm3;
    ResultSet Rs, Rs1;
    DefaultTableModel model = new DefaultTableModel();
    double totalS = 0;
    double totalE = 0;
    double solde = 0;
    String nan = "", sold = "";
    String mE = "", mS = "";

    public Etat() {
        initComponents();
        model.addColumn("Date");
        model.addColumn("Client");
        model.addColumn("Produit");
        model.addColumn("Montant Entrée");
        model.addColumn("Montant Sortie");

        try {
            stm = con.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("select entree.dateEntree as 'dateE', entree.montantEntree as 'montantEntree',sum(entree.montantEntree) as 'totalEntree', entree.nomClient as 'nomClient' from entree order by dateEntree desc");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("dateE"), Rs.getString("nomClient"), nan, Rs.getString("montantEntree"), nan});
                totalE = Double.parseDouble(Rs.getString("totalEntree"));
            }

            stm1 = con.obtenirConnexion().createStatement();
            ResultSet Rs1 = stm1.executeQuery("select sortie.dateSortie as 'dateS',sum(sortie.qteSortie * produit.pu) as 'montantS',sortie.designProduit as 'design', sortie.nomClient as 'nomClient' from sortie,produit group by sortie.dateSortie, sortie.nomClient, sortie.designProduit order by sortie.dateSortie desc");
            while (Rs1.next()) {
                model.addRow(new Object[]{Rs1.getString("dateS"), Rs1.getString("nomClient"), Rs1.getString("design"), nan, Rs1.getString("montantS")});
                totalS = totalS + Double.parseDouble(Rs1.getString("montantS"));
            }
            mS = String.valueOf(totalS);
            lbl_TSortie.setText(mS);
            mE = String.valueOf(totalE);
            lbl_Tentree.setText(mE);
            solde = totalE - totalS;
            sold = String.valueOf(solde);
            lbl_TotalSold.setText(sold);
        } catch (SQLException e) {
            System.err.println(e);
        }

        tblEtat.setModel(model);
    }

    private void affiche() {
        try {
            model.setRowCount(0);
            stm = con.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("select entree.dateEntree as 'dateE', entree.montantEntree as 'montantEntree',sum(entree.montantEntree) as 'totalEntree', entree.nomClient as 'nomClient' from entree order by dateEntree desc");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("dateE"), Rs.getString("nomClient"), nan, Rs.getString("montantEntree"), nan});
                totalE = Double.parseDouble(Rs.getString("totalEntree"));
            }

            stm1 = con.obtenirConnexion().createStatement();
            ResultSet Rs1 = stm1.executeQuery("select sortie.dateSortie as 'dateS',sum(sortie.qteSortie * produit.pu) as 'montantS',sortie.designProduit as 'design', sortie.nomClient as 'nomClient' from sortie,produit group by sortie.dateSortie, sortie.nomClient, sortie.designProduit order by sortie.dateSortie desc");
            while (Rs1.next()) {
                model.addRow(new Object[]{Rs1.getString("dateS"), Rs1.getString("nomClient"), Rs1.getString("design"), nan, Rs1.getString("montantS")});
                totalS = totalS + Double.parseDouble(Rs1.getString("montantS"));
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        tblEtat.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuEtat = new javax.swing.JLabel();
        menuEntree = new javax.swing.JLabel();
        menuSortie = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEtat = new javax.swing.JTable();
        txt_rechercheSortie = new javax.swing.JTextField();
        dt_sortieRecherche2 = new com.toedter.calendar.JDateChooser();
        dt_sortieRecherche3 = new com.toedter.calendar.JDateChooser();
        btn_sortieRecherche = new javax.swing.JButton();
        btn_clientActualiser = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_TotalSold = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_TSortie = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_Tentree = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        menuAdmin = new javax.swing.JLabel();
        menuClient = new javax.swing.JLabel();
        menuProduit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(121, 45, 49));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuEtat.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuEtat.setForeground(new java.awt.Color(255, 255, 255));
        menuEtat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sales Performance_50px.png"))); // NOI18N
        menuEtat.setText("ETAT");
        jPanel1.add(menuEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, -1));

        menuEntree.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuEntree.setForeground(new java.awt.Color(255, 255, 255));
        menuEntree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jog Forward_48px.png"))); // NOI18N
        menuEntree.setText("ENTREE");
        menuEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEntreeMouseClicked(evt);
            }
        });
        jPanel1.add(menuEntree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, -1));

        menuSortie.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuSortie.setForeground(new java.awt.Color(255, 255, 255));
        menuSortie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jog Reverse_48px.png"))); // NOI18N
        menuSortie.setText("SORTIE");
        menuSortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSortieMouseClicked(evt);
            }
        });
        jPanel1.add(menuSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 140, 380));

        jPanel2.setBackground(new java.awt.Color(176, 143, 135));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_100px.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Male User_100px.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 100));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LES ENTRES/SORTIES");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 400, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 930, 100));

        jPanel3.setBackground(new java.awt.Color(246, 144, 42));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEtat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEtat);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 640, 270));

        txt_rechercheSortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_rechercheSortieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_rechercheSortieMouseExited(evt);
            }
        });
        jPanel3.add(txt_rechercheSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 30));

        dt_sortieRecherche2.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(dt_sortieRecherche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 120, 30));

        dt_sortieRecherche3.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(dt_sortieRecherche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 30));

        btn_sortieRecherche.setText("Rechercher");
        btn_sortieRecherche.setMaximumSize(new java.awt.Dimension(87, 50));
        btn_sortieRecherche.setPreferredSize(new java.awt.Dimension(90, 45));
        btn_sortieRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortieRechercheActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sortieRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 30));

        btn_clientActualiser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clientActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Synchronize_48px.png"))); // NOI18N
        btn_clientActualiser.setText("ACTUALISER");
        btn_clientActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientActualiserActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clientActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 660, 380));

        jPanel4.setBackground(new java.awt.Color(176, 143, 135));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Solde:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 90, 26));

        lbl_TotalSold.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TotalSold.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TotalSold.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_TotalSold.setText("0000");
        jPanel4.add(lbl_TotalSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 110, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Sortie:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Entree:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 26));

        lbl_TSortie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TSortie.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TSortie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_TSortie.setText("0000");
        jPanel4.add(lbl_TSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, 26));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ar");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 26));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ar");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 26));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ar");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 26));

        lbl_Tentree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Tentree.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tentree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Tentree.setText("0000");
        jPanel4.add(lbl_Tentree, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 26));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 479, 930, 100));

        jPanel5.setBackground(new java.awt.Color(121, 45, 49));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuAdmin.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuAdmin.setForeground(new java.awt.Color(255, 255, 255));
        menuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer_50px.png"))); // NOI18N
        menuAdmin.setText("COMPTE");
        menuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdminMouseClicked(evt);
            }
        });
        jPanel5.add(menuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, -1));

        menuClient.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuClient.setForeground(new java.awt.Color(255, 255, 255));
        menuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hard Working_48px.png"))); // NOI18N
        menuClient.setText("CLIENT");
        menuClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientMouseClicked(evt);
            }
        });
        jPanel5.add(menuClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 110, -1));

        menuProduit.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuProduit.setForeground(new java.awt.Color(255, 255, 255));
        menuProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Buying_48px.png"))); // NOI18N
        menuProduit.setText("PRODUIT");
        menuProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProduitMouseClicked(evt);
            }
        });
        jPanel5.add(menuProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 110, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 130, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdminMouseClicked
        new Admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAdminMouseClicked

    private void menuClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientMouseClicked
        new Client().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuClientMouseClicked

    private void menuProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProduitMouseClicked
        new Produit().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuProduitMouseClicked

    private void menuEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEntreeMouseClicked
        new Entree().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEntreeMouseClicked

    private void menuSortieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSortieMouseClicked
        new Sortie().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuSortieMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Authentification().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void txt_rechercheSortieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_rechercheSortieMouseEntered

    }//GEN-LAST:event_txt_rechercheSortieMouseEntered

    private void txt_rechercheSortieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_rechercheSortieMouseExited

    }//GEN-LAST:event_txt_rechercheSortieMouseExited

    private void btn_sortieRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortieRechercheActionPerformed

        String recherche1 = txt_rechercheSortie.getText();
        String date1 = ((JTextField) dt_sortieRecherche3.getDateEditor().getUiComponent()).getText();
        String date2 = ((JTextField) dt_sortieRecherche2.getDateEditor().getUiComponent()).getText();

        try {
            model.setRowCount(0);
            if (recherche1.equals("")) {
                stm = con.obtenirConnexion().createStatement();
                ResultSet Rs2 = stm.executeQuery("SELECT entree.dateEntree AS 'dateE', entree.montantEntree AS 'montantEntree',SUM(entree.montantEntree) AS 'totalEntree', entree.nomClient AS 'nomClient' FROM entree WHERE  dateEntree BETWEEN '" + date2 + "' AND '" + date1 + "' ");
                while (Rs2.next()) {
                    model.addRow(new Object[]{Rs2.getString("dateE"), Rs2.getString("nomClient"), nan, Rs2.getString("montantEntree"), nan});
                    //   totalE = Double.parseDouble(Rs.getString("totalEntree"));
                }
                stm1 = con.obtenirConnexion().createStatement();
                Rs1 = stm1.executeQuery("select sortie.dateSortie as 'dateS',sum(sortie.qteSortie * produit.pu) as 'montantS',sortie.designProduit as 'design', sortie.nomClient as 'nomClient' from sortie,produit WHERE sortie.dateSortie BETWEEN '" + date2 + "' AND '" + date1 + "' group by sortie.dateSortie, sortie.nomClient, sortie.designProduit order by sortie.dateSortie desc");
                while (Rs1.next()) {
                    model.addRow(new Object[]{Rs1.getString("dateS"), Rs1.getString("nomClient"), Rs1.getString("design"), nan, Rs1.getString("montantS")});
                    //   totalS = totalS + Double.parseDouble(Rs1.getString("montantS"));
                }
                txt_rechercheSortie.setText("");
                ((JTextField) dt_sortieRecherche2.getDateEditor().getUiComponent()).setText("");
                ((JTextField) dt_sortieRecherche3.getDateEditor().getUiComponent()).setText("");

            } else if (date1.equals("") && date2.equals("")) {
                stm = con.obtenirConnexion().createStatement();
                ResultSet Rs2 = stm.executeQuery("SELECT entree.dateEntree AS 'dateE', entree.montantEntree AS 'montantEntree',SUM(entree.montantEntree) AS 'totalEntree', entree.nomClient AS 'nomClient' FROM entree WHERE entree.nomClient LIKE '%" + recherche1 + "%'");
                while (Rs2.next()) {
                    model.addRow(new Object[]{Rs2.getString("dateE"), Rs2.getString("nomClient"), nan, Rs2.getString("montantEntree"), nan});
                    //  totalE = Double.parseDouble(Rs.getString("totalEntree"));
                }
                stm1 = con.obtenirConnexion().createStatement();
                Rs1 = stm1.executeQuery("select sortie.dateSortie as 'dateS',sum(sortie.qteSortie * produit.pu) as 'montantS',sortie.designProduit as 'design', sortie.nomClient as 'nomClient' from sortie,produit WHERE sortie.nomClient LIKE '%" + recherche1 + "%' OR sortie.designProduit LIKE '%" + recherche1 + "%' group by sortie.dateSortie, sortie.nomClient, sortie.designProduit order by sortie.dateSortie desc");
                while (Rs1.next()) {
                    model.addRow(new Object[]{Rs1.getString("dateS"), Rs1.getString("nomClient"), Rs1.getString("design"), nan, Rs1.getString("montantS")});
                    // totalS = totalS + Double.parseDouble(Rs1.getString("montantS"));
                }

                txt_rechercheSortie.setText("");
                ((JTextField) dt_sortieRecherche2.getDateEditor().getUiComponent()).setText("");
                ((JTextField) dt_sortieRecherche3.getDateEditor().getUiComponent()).setText("");

            }

        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_sortieRechercheActionPerformed

    private void btn_clientActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientActualiserActionPerformed
        affiche();
    }//GEN-LAST:event_btn_clientActualiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clientActualiser;
    private javax.swing.JButton btn_sortieRecherche;
    public static com.toedter.calendar.JDateChooser dt_sortieRecherche2;
    public static com.toedter.calendar.JDateChooser dt_sortieRecherche3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_TSortie;
    private javax.swing.JLabel lbl_Tentree;
    private javax.swing.JLabel lbl_TotalSold;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuAdmin;
    private javax.swing.JLabel menuClient;
    private javax.swing.JLabel menuEntree;
    private javax.swing.JLabel menuEtat;
    private javax.swing.JLabel menuProduit;
    private javax.swing.JLabel menuSortie;
    private javax.swing.JTable tblEtat;
    private javax.swing.JTextField txt_rechercheSortie;
    // End of variables declaration//GEN-END:variables
}
