/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import form.FormProduits;
import form.FormProduitsModifier;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login.Admin;
import login.Authentification;

/**
 *
 * @author RANDRIAMANANTSOA
 */
public class Produit extends javax.swing.JFrame {

    Connecter con = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model = new DefaultTableModel();

    public Produit() {
        initComponents();
        model.addColumn("Id");
        model.addColumn("N°Produit");
        model.addColumn("Designation");
        model.addColumn("Prix Unitaire(Ar)");
        model.addColumn("Stock");
        try {
            stm = con.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("select * from produit");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("idProduit"), Rs.getString("numProduit"), Rs.getString("designProduit"), Rs.getString("pu"), Rs.getString("stock")});
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        tblProduit.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuEtat = new javax.swing.JLabel();
        menuEntree = new javax.swing.JLabel();
        menuSortie = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduit = new javax.swing.JTable();
        txt_rechercheProduit = new javax.swing.JTextField();
        lbl_produitRecherche = new javax.swing.JLabel();
        btn_produitAjouter = new javax.swing.JButton();
        btn_produitModifier = new javax.swing.JButton();
        btn_produitSupprimer = new javax.swing.JButton();
        btn_ProduitActualiser = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        menuAdmin = new javax.swing.JLabel();
        menuClient = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(121, 45, 49));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuEtat.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuEtat.setForeground(new java.awt.Color(255, 255, 255));
        menuEtat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sales Performance_50px.png"))); // NOI18N
        menuEtat.setText("ETAT");
        menuEtat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEtatMouseClicked(evt);
            }
        });
        jPanel1.add(menuEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, -1));

        menuEntree.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuEntree.setForeground(new java.awt.Color(255, 255, 255));
        menuEntree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jog Forward_48px.png"))); // NOI18N
        menuEntree.setText("ENTREE");
        menuEntree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEntreeMouseClicked(evt);
            }
        });
        jPanel1.add(menuEntree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, -1));

        menuSortie.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuSortie.setForeground(new java.awt.Color(255, 255, 255));
        menuSortie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Jog Reverse_48px.png"))); // NOI18N
        menuSortie.setText("SORTIE");
        menuSortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSortieMouseClicked(evt);
            }
        });
        jPanel1.add(menuSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 140, 380));

        jPanel2.setBackground(new java.awt.Color(176, 143, 135));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shutdown_100px.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Male User_100px.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 100));

        jLabel9.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRODUITS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        jPanel3.setBackground(new java.awt.Color(246, 144, 42));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProduit);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 640, 240));

        txt_rechercheProduit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_rechercheProduitInputMethodTextChanged(evt);
            }
        });
        txt_rechercheProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rechercheProduitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rechercheProduitKeyTyped(evt);
            }
        });
        jPanel3.add(txt_rechercheProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 30));

        lbl_produitRecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search_35px.png"))); // NOI18N
        lbl_produitRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_produitRechercheMouseClicked(evt);
            }
        });
        jPanel3.add(lbl_produitRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        btn_produitAjouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_produitAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Plus_35px.png"))); // NOI18N
        btn_produitAjouter.setText("NOUVEAU");
        btn_produitAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produitAjouterActionPerformed(evt);
            }
        });
        jPanel3.add(btn_produitAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 40));

        btn_produitModifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_produitModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit_35px.png"))); // NOI18N
        btn_produitModifier.setText("MODIFIER");
        btn_produitModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produitModifierActionPerformed(evt);
            }
        });
        jPanel3.add(btn_produitModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 160, 40));

        btn_produitSupprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_produitSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete_35px.png"))); // NOI18N
        btn_produitSupprimer.setText("SUPPRIMER");
        btn_produitSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produitSupprimerActionPerformed(evt);
            }
        });
        jPanel3.add(btn_produitSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 150, 40));

        btn_ProduitActualiser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ProduitActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Synchronize_48px.png"))); // NOI18N
        btn_ProduitActualiser.setText("ACTUALISER");
        btn_ProduitActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProduitActualiserActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ProduitActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 180, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 660, 380));

        jPanel4.setBackground(new java.awt.Color(176, 143, 135));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 479, 930, 100));

        jPanel5.setBackground(new java.awt.Color(121, 45, 49));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuAdmin.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuAdmin.setForeground(new java.awt.Color(255, 255, 255));
        menuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer_50px.png"))); // NOI18N
        menuAdmin.setText("COMPTE");
        menuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdminMouseClicked(evt);
            }
        });
        jPanel5.add(menuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, -1));

        menuClient.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        menuClient.setForeground(new java.awt.Color(255, 255, 255));
        menuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hard Working_48px.png"))); // NOI18N
        menuClient.setText("CLIENT");
        menuClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientMouseClicked(evt);
            }
        });
        jPanel5.add(menuClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 110, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Buying_48px.png"))); // NOI18N
        jLabel7.setText("PRODUIT");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 110, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 130, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void affiche() {
        try {
            txt_rechercheProduit.setText("");
            model.setRowCount(0);
            stm = con.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("select * from produit");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("idProduit"), Rs.getString("numProduit"), Rs.getString("designProduit"), Rs.getString("pu"), Rs.getString("stock")});
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        tblProduit.setModel(model);
    }
    private void menuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdminMouseClicked
        new Admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAdminMouseClicked

    private void menuClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientMouseClicked
        new Client().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuClientMouseClicked

    private void menuEntreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEntreeMouseClicked
        new Entree().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEntreeMouseClicked

    private void menuSortieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSortieMouseClicked
        new Sortie().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuSortieMouseClicked

    private void menuEtatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEtatMouseClicked
        new Etat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuEtatMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Authentification().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void btn_produitAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produitAjouterActionPerformed
        new FormProduits().setVisible(true);
    }//GEN-LAST:event_btn_produitAjouterActionPerformed

    private void btn_produitModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produitModifierActionPerformed
        TableModel model1 = tblProduit.getModel();
        int indexs[] = tblProduit.getSelectedRows();

        Object[] row = new Object[1];
        FormProduitsModifier frm2 = new FormProduitsModifier();
        for (int i = 0; i < indexs.length; i++) {
            FormProduitsModifier.txt_produitModifierId.setText((String) model1.getValueAt(indexs[i], 0));
            FormProduitsModifier.txt_produitModifierNumero.setText((String) model1.getValueAt(indexs[i], 1));
            FormProduitsModifier.txt_produitModifierDesignation.setText((String) model1.getValueAt(indexs[i], 2));
            FormProduitsModifier.txt_produitModifierPu.setText((String) model1.getValueAt(indexs[i], 3));
            FormProduitsModifier.txt_produitModifierStock.setText((String) model1.getValueAt(indexs[i], 4));
        }
        frm2.setVisible(true);
    }//GEN-LAST:event_btn_produitModifierActionPerformed

    private void btn_produitSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produitSupprimerActionPerformed
        TableModel model1 = tblProduit.getModel();
        int indexs[] = tblProduit.getSelectedRows();
        String id, num, design, pu, stock;
        Object[] row = new Object[1];

        for (int i = 0; i < indexs.length; i++) {
            id = (String) model1.getValueAt(indexs[i], 0);
            num = (String) model1.getValueAt(indexs[i], 1);
            design = (String) model1.getValueAt(indexs[i], 2);
            pu = (String) model1.getValueAt(indexs[i], 3);
            stock = (String) model1.getValueAt(indexs[i], 4);
            try {
                stm = con.obtenirConnexion().createStatement();
                if (JOptionPane.showConfirmDialog(null, "Vous voulez vraiment supprimer", "suppression",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    if (id.length() != 0) {
                        stm.executeUpdate("DELETE from produit WHERE idProduit=" + id);
                        affiche();
                    } else {
                        JOptionPane.showConfirmDialog(null, "Veuillez remplir le champ id");
                    }
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Erreur de suppression !" + e.getMessage());
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btn_produitSupprimerActionPerformed

    private void btn_ProduitActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProduitActualiserActionPerformed
        affiche();
    }//GEN-LAST:event_btn_ProduitActualiserActionPerformed

    private void txt_rechercheProduitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheProduitKeyPressed

    }//GEN-LAST:event_txt_rechercheProduitKeyPressed

    private void txt_rechercheProduitInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_rechercheProduitInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheProduitInputMethodTextChanged

    private void txt_rechercheProduitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheProduitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheProduitKeyTyped

    private void lbl_produitRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_produitRechercheMouseClicked
        try {
            model.setRowCount(0);
            {
                Rs = stm.executeQuery("SELECT * from produit WHERE numProduit LIKE '%" + txt_rechercheProduit.getText() + "%' OR designProduit LIKE '%" + txt_rechercheProduit.getText() + "%' OR pu LIKE '%" + txt_rechercheProduit.getText() + "%' OR stock LIKE '%" + txt_rechercheProduit.getText() + "%' ");
                txt_rechercheProduit.setText("");
            }
            while (Rs.next()) {
                Object[] produit = {Rs.getString("idProduit"), Rs.getString("numProduit"), Rs.getString("designProduit"), Rs.getString("pu"), Rs.getString("stock")};
                model.addRow(produit);
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Aucun produit correspond a ce numero !");
                }
            }
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_lbl_produitRechercheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Produit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ProduitActualiser;
    private javax.swing.JButton btn_produitAjouter;
    private javax.swing.JButton btn_produitModifier;
    private javax.swing.JButton btn_produitSupprimer;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_produitRecherche;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuAdmin;
    private javax.swing.JLabel menuClient;
    private javax.swing.JLabel menuEntree;
    private javax.swing.JLabel menuEtat;
    private javax.swing.JLabel menuSortie;
    private javax.swing.JTable tblProduit;
    private javax.swing.JTextField txt_rechercheProduit;
    // End of variables declaration//GEN-END:variables
}
