/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import gestion.Client;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RANDRIAMANANTSOA
 */
public class FormClient extends javax.swing.JFrame {

    Connecter con = new Connecter();
    Client cli = new Client();
    Statement stm;
    ResultSet Rs;

    public FormClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_cliAnnulAjouter = new javax.swing.JButton();
        btn_cliAjouter = new javax.swing.JButton();
        txt_cliAdresseAjouter = new javax.swing.JTextField();
        txt_cliNomAjouter = new javax.swing.JTextField();
        txt_cliContactAjouter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(134, 23, 70));
        jPanel1.setMaximumSize(new java.awt.Dimension(430, 442));
        jPanel1.setMinimumSize(new java.awt.Dimension(430, 442));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 442));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adresse :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 30));

        btn_cliAnnulAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel_35px.png"))); // NOI18N
        btn_cliAnnulAjouter.setText("ANNULER");
        btn_cliAnnulAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cliAnnulAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cliAnnulAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 130, 50));

        btn_cliAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Checkmark_35px.png"))); // NOI18N
        btn_cliAjouter.setText("VALIDER");
        btn_cliAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cliAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cliAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 50));
        jPanel1.add(txt_cliAdresseAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 230, 30));
        jPanel1.add(txt_cliNomAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, 30));
        jPanel1.add(txt_cliContactAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cliAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cliAjouterActionPerformed

        String nom = txt_cliNomAjouter.getText();
        String idCli = "0";
        String adresse = txt_cliAdresseAjouter.getText();
        String contact = txt_cliContactAjouter.getText();
        if (nom.equals("") && adresse.equals("") && contact.equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez completer tous les champs svp!");
        } else {
            String requete = "INSERT INTO client(idClient,nomClient,addresse,contact) VALUES ('" + idCli + "','" + nom + "','" + adresse + "','" + contact + "')";

            try {
                stm = con.obtenirConnexion().createStatement();
                stm.executeUpdate(requete);
                JOptionPane.showMessageDialog(null, "Ajoute avec succes");

                txt_cliNomAjouter.setText("");
                txt_cliAdresseAjouter.setText("");
                txt_cliContactAjouter.setText("");

                cli.affiche();
                this.setVisible(false);
            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }
    }//GEN-LAST:event_btn_cliAjouterActionPerformed

    private void btn_cliAnnulAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cliAnnulAjouterActionPerformed

        txt_cliNomAjouter.setText("");
        txt_cliAdresseAjouter.setText("");
        txt_cliContactAjouter.setText("");
    }//GEN-LAST:event_btn_cliAnnulAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cliAjouter;
    private javax.swing.JButton btn_cliAnnulAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_cliAdresseAjouter;
    private javax.swing.JTextField txt_cliContactAjouter;
    private javax.swing.JTextField txt_cliNomAjouter;
    // End of variables declaration//GEN-END:variables
}
