/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import gestion.Client;
import gestion.Produit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RANDRIAMANANTSOA
 */
public class FormProduitsModifier extends javax.swing.JFrame {

    Connecter con = new Connecter();
    Statement stm;
    ResultSet Rs;
    Produit prod = new Produit();

    public FormProduitsModifier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_produitModifierDesignation = new javax.swing.JTextField();
        txt_produitModifierId = new javax.swing.JTextField();
        txt_produitModifierPu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_produitModifierAnnuler = new javax.swing.JButton();
        btn_produitModifierValide = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_produitModifierStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_produitModifierNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 124, 250));
        jPanel1.setMaximumSize(new java.awt.Dimension(432, 528));
        jPanel1.setMinimumSize(new java.awt.Dimension(432, 528));
        jPanel1.setPreferredSize(new java.awt.Dimension(432, 528));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prix Unitaire :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 30));
        jPanel1.add(txt_produitModifierDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, 30));

        txt_produitModifierId.setEditable(false);
        jPanel1.add(txt_produitModifierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 30));
        jPanel1.add(txt_produitModifierPu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designation :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 30));

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUIT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 200, -1));

        btn_produitModifierAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel_35px.png"))); // NOI18N
        btn_produitModifierAnnuler.setText("ANNULER");
        jPanel1.add(btn_produitModifierAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 130, 50));

        btn_produitModifierValide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Checkmark_35px.png"))); // NOI18N
        btn_produitModifierValide.setText("VALIDER");
        btn_produitModifierValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produitModifierValideActionPerformed(evt);
            }
        });
        jPanel1.add(btn_produitModifierValide, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre stock:");
        jLabel5.setMaximumSize(new java.awt.Dimension(432, 528));
        jLabel5.setMinimumSize(new java.awt.Dimension(432, 528));
        jLabel5.setPreferredSize(new java.awt.Dimension(432, 528));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 30));
        jPanel1.add(txt_produitModifierStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 30));
        jPanel1.add(txt_produitModifierNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produitModifierValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produitModifierValideActionPerformed
        try {
            stm = con.obtenirConnexion().createStatement();
            if (JOptionPane.showConfirmDialog(null, "Vous voulez vraiment modifier", "modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {

                stm.executeUpdate("UPDATE produit SET numProduit='" + txt_produitModifierNumero.getText() + "',designProduit='" + txt_produitModifierDesignation.getText() + "',pu='" + txt_produitModifierPu.getText() + "',stock='" + txt_produitModifierStock.getText() + "' WHERE idProduit=" + txt_produitModifierId.getText());
                txt_produitModifierId.setText("");
                txt_produitModifierNumero.setText("");
                txt_produitModifierDesignation.setText("");
                txt_produitModifierPu.setText("");
                txt_produitModifierStock.setText("");

                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de modification !" + e.getMessage());
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_produitModifierValideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduitsModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduitsModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduitsModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduitsModifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduitsModifier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_produitModifierAnnuler;
    private javax.swing.JButton btn_produitModifierValide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txt_produitModifierDesignation;
    public static javax.swing.JTextField txt_produitModifierId;
    public static javax.swing.JTextField txt_produitModifierNumero;
    public static javax.swing.JTextField txt_produitModifierPu;
    public static javax.swing.JTextField txt_produitModifierStock;
    // End of variables declaration//GEN-END:variables
}
