/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author RANDRIAMANANTSOA
 */
public class FormSortie extends javax.swing.JFrame {

    Connecter con = new Connecter();
    Statement stm, stm1;
    ResultSet Rs;
    ResultSet Rs1;

    public FormSortie() {
        initComponents();
        Mitady_client();
        Mitady_produit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_sortieQte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dt_sortie = new com.toedter.calendar.JDateChooser();
        cbx_produitSortie = new javax.swing.JComboBox<>();
        cbx_clientSortie = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(86, 115, 154));
        jPanel1.setMaximumSize(new java.awt.Dimension(430, 442));
        jPanel1.setMinimumSize(new java.awt.Dimension(430, 442));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 442));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SORTIE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantité sortie :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom Client :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel_35px.png"))); // NOI18N
        jButton1.setText("ANNULER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 130, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Checkmark_35px.png"))); // NOI18N
        jButton2.setText("VALIDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 120, 50));
        jPanel1.add(txt_sortieQte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom produit :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 30));

        dt_sortie.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dt_sortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 210, 30));

        jPanel1.add(cbx_produitSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 210, 30));

        jPanel1.add(cbx_clientSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String dateSortie = ((JTextField) dt_sortie.getDateEditor().getUiComponent()).getText();
        String idSortie = "0";
        String nomCli = cbx_clientSortie.getSelectedItem().toString();
        String nomProd = cbx_produitSortie.getSelectedItem().toString();
        String qte = txt_sortieQte.getText();
        if (dateSortie.equals("") && nomCli.equals("") && nomProd.equals("") && qte.equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez completer tous les champs svp!");
        } else {
            String requete = "INSERT INTO sortie(idSortie,dateSortie,nomClient,designProduit, qteSortie) VALUES ('" + idSortie + "','" + dateSortie + "','" + nomCli + "','" + nomProd + "','" + qte + "')";

            try {
                stm = con.obtenirConnexion().createStatement();
                stm.executeUpdate(requete);
                JOptionPane.showMessageDialog(null, "Ajoute avec succes");
                stm1.executeUpdate("UPDATE produit SET stock= (stock - '" + qte + "') WHERE designProduit='" + nomProd + "'");
                ((JTextField) dt_sortie.getDateEditor().getUiComponent()).setText("");
                cbx_clientSortie.getSelectedItem().toString();
                cbx_produitSortie.getSelectedItem().toString();
                txt_sortieQte.setText("");

                this.setVisible(false);
            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ((JTextField) dt_sortie.getDateEditor().getUiComponent()).setText("");
        cbx_clientSortie.getSelectedItem().toString();
        cbx_produitSortie.getSelectedItem().toString();
        txt_sortieQte.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    public void Mitady_client() {

        try {

            stm = con.obtenirConnexion().createStatement();
            Rs = stm.executeQuery("select * from client");
            while (Rs.next()) {
                String NomClient = Rs.getString("nomClient");
                cbx_clientSortie.addItem(NomClient);
            }

        } catch (SQLException ex) {
            Logger.getLogger(FormEntree.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    public void Mitady_produit() {

        try {

            stm1 = con.obtenirConnexion().createStatement();
            Rs1 = stm1.executeQuery("select * from produit");
            while (Rs1.next()) {
                String NumProduit = Rs1.getString("designProduit");
                cbx_produitSortie.addItem(NumProduit);
            }

        } catch (SQLException ex) {
            Logger.getLogger(FormEntree.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSortie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_clientSortie;
    private javax.swing.JComboBox<String> cbx_produitSortie;
    private com.toedter.calendar.JDateChooser dt_sortie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_sortieQte;
    // End of variables declaration//GEN-END:variables
}
